server.port=8080

app.jwt.secret=change-this-secret-key-please-256bit
app.jwt.expiration=86400000

spring.application.name=testCinema

logging.level.com.cinema.testcinema.security=ERROR

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=test_user
spring.datasource.password=pass1

omdb.api.key=aee5595e
# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never
